name: Swift

on: [push]

jobs:
  test:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - name: Trigger tests
      run: |
        swift test
